server:
  port: 8756
  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: TRAVELNOTES-MESSAGES
        uri: http://localhost:8084

        predicates:
        - Path=/api/**



        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
